// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZcwTYizgdIg7qjMfa3da1MXD-rMMC8DY',
    appId: '1:779844169649:web:5f379a5f6e8f0759e55790',
    messagingSenderId: '779844169649',
    projectId: 'quiz-app-iota-arham-1234-3d07c',
    authDomain: 'quiz-app-iota-arham-1234-3d07c.firebaseapp.com',
    storageBucket: 'quiz-app-iota-arham-1234-3d07c.firebasestorage.app',
    measurementId: 'G-JZE9VZE039',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkbcLQY9ox-2FjhD9TqGIGUsNmg8BL4ew',
    appId: '1:779844169649:android:d2fdace2cb294cdde55790',
    messagingSenderId: '779844169649',
    projectId: 'quiz-app-iota-arham-1234-3d07c',
    storageBucket: 'quiz-app-iota-arham-1234-3d07c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7EQ29b0w5dzmcFToWadoKTW01QM4Tjo',
    appId: '1:779844169649:ios:e86af8ddec963b9ee55790',
    messagingSenderId: '779844169649',
    projectId: 'quiz-app-iota-arham-1234-3d07c',
    storageBucket: 'quiz-app-iota-arham-1234-3d07c.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx7EQ29b0w5dzmcFToWadoKTW01QM4Tjo',
    appId: '1:779844169649:ios:e86af8ddec963b9ee55790',
    messagingSenderId: '779844169649',
    projectId: 'quiz-app-iota-arham-1234-3d07c',
    storageBucket: 'quiz-app-iota-arham-1234-3d07c.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );
}
